spring:
  datasource:
    url: jdbc:mysql://localhost:3306/exercise_shop
    username: root
    password: 123
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect


  data:
    redis:
      host: localhost
      port: 6379

  task:
    scheduling:
      pool:
        size: 10
      thread-name-prefix: schedule-task-

  elasticsearch:
    uris: http://localhost:9200
    username: elastic
    password: 123


#  flyway:
#    url: jdbc:mysql://localhost:3306/exercise_shop
#    user: root
#    password: 123
#    enabled: true
#    locations: classpath:db/migration
#    baseline-version: 1
#    baseline-on-migrate: true

jwt:
  signer-key: "bTjB9aNwmnrGaTjQEBciTlZlC6iYu3q8uqOCQbIX25FSgkDBLnQ+m6yMZOX1VqJU"
  access:
    expiration: "20" #in second
  refresh:
    expiration: "12000" #in second

init:
  admin-password: "@Admin123"

application:
  time-reserve-product: "60" #in second
